[rospy.client][INFO] 2020-09-02 04:09:06,760: init_node, name[/rostopic_2555_1599019746711], pid[2555]
[xmlrpc][INFO] 2020-09-02 04:09:06,761: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-02 04:09:06,762: Started XML-RPC server [http://192.168.137.54:36191/]
[rospy.init][INFO] 2020-09-02 04:09:06,762: ROS Slave URI: [http://192.168.137.54:36191/]
[rospy.impl.masterslave][INFO] 2020-09-02 04:09:06,763: _ready: http://192.168.137.54:36191/
[rospy.registration][INFO] 2020-09-02 04:09:06,764: Registering with master node http://192.168.137.54:11311
[xmlrpc][INFO] 2020-09-02 04:09:06,764: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-02 04:09:06,863: registered with master
[rospy.rosout][INFO] 2020-09-02 04:09:06,864: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-02 04:09:06,872: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-02 04:09:06,876: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-02 04:09:07,130: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-02 04:09:07,149: topic[/camera/rgb/image_raw] adding connection to [http://192.168.137.54:37013/], count 0
[rospy.msg][ERROR] 2020-09-02 04:09:07,190: cannot deserialize message: EXCEPTION Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 223, in deserialize_messages
    msg_queue.append(data.deserialize(q))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_Image.py", line 147, in deserialize
    codecs.lookup_error("rosmsg").msg_type = self._type
LookupError: unknown error handler name 'rosmsg'

[rospy.internal][ERROR] 2020-09-02 04:09:07,192: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 735, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 398, in read_messages
    deserialize_messages(b, msg_queue, self.recv_data_class, queue_size=self.queue_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 245, in deserialize_messages
    raise genpy.DeserializationError("cannot deserialize: %s"%str(e))
DeserializationError: cannot deserialize: unknown error handler name 'rosmsg'

[rospy.internal][WARNING] 2020-09-02 04:09:07,196: Unknown error initiating TCP/IP socket to 192.168.137.54:40247 (http://192.168.137.54:37013/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 378, in read_ros_handshake_header
    return decode_ros_handshake_header(bval)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 339, in decode_ros_handshake_header
    raise ROSHandshakeException("Invalid line in handshake header: [%s]"%line)
ROSHandshakeException: Invalid line in handshake header: [ã]

[rospy.internal][INFO] 2020-09-02 04:09:07,197: topic[/camera/rgb/image_raw] removing connection to http://192.168.137.54:37013/
[rospy.core][INFO] 2020-09-02 04:09:21,727: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-09-02 04:09:21,738: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-09-02 04:09:21,739: signal-2
[rospy.core][INFO] 2020-09-02 04:09:21,904: signal_shutdown [atexit]
